### ISSUE TITLE
Not enough information parsed from response

### ISSUE THREAD

**Issue by sadikoff** [qdequippe/oauth2-symfony-connect#1]
Hey, I tried to use your bundle to create an oauth2 connection with SymfonyConnect and found that I can't link accounts with email, because ResourceOwner doesn't parse this info from the OAuth response. Is it possible to fix it? Or probably there is a workaround?

**Comment by qdequippe** [comment]
@sadikoff feel free to fix it in a pull request, I will be happy to merge it ;)

You can check how to get the email here https://github.com/symfonycorp/connect/blob/master/src/Api/Parser/VndComSymfonyConnectXmlParser.php#L173

**Comment by sadikoff** [comment]
@qdequippe Woohoo! Nice! Just wanted to check if you still support it =) I'll make a PR soon 🍺
